famous_quotes/app_auth/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from . import views
from .forms import LoginForm

app_name = "app_auth"

urlpatterns = [
    path("signup/", views.RegisterView.as_view(), name="signup"),
    path(
        "signin/",
        LoginView.as_view(
            template_name="app_auth/login.html",
            form_class=LoginForm,
            redirect_authenticated_user=True,
        ),
        name="signin",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password_reset/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="app_auth/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="app_auth/password_reset_confirm.html",
            success_url="/auth/password_reset/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="app_auth/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

famous_quotes/famous_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

"""
URL configuration for famous_quotes project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("auth/", include("app_auth.urls")),
]

famous_quotes/quotes/urls.py
from django.urls import path

from .views import QuotesListView, AuthorDetailView, AuthorCreateView, QuoteCreateView

app_name = "quotes"

urlpatterns = [
    path("", QuotesListView.as_view(), name="home"),  # quotes:home
    path(
        "author/<slug:slug>/", AuthorDetailView.as_view(), name="author"
    ),  # quotes:author
    path(
        "add-author", AuthorCreateView.as_view(), name="add_author"
    ),  # quotes:add_author
    path("add-quote", QuoteCreateView.as_view(), name="add_quote"),  # quotes:add_quote
]

famous_quotes/app_auth/models.py
from django.db import models

# Create your models here.

famous_quotes/app_auth/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, EmailField, TextInput, EmailInput, PasswordInput


class RegistrationForm(UserCreationForm):
    username = CharField(
        max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"})
    )

    email = EmailField(
        max_length=100,
        required=True,
        widget=EmailInput(attrs={"class": "form-control"}),
    )

    password1 = CharField(
        max_length=50,
        required=True,
        widget=PasswordInput(attrs={"class": "form-control"}),
    )

    password2 = CharField(
        max_length=50,
        required=True,
        widget=PasswordInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class LoginForm(AuthenticationForm):
    username = CharField(
        max_length=100, required=True, widget=TextInput(attrs={"class": "form-control"})
    )

    password = CharField(
        max_length=50,
        required=True,
        widget=PasswordInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = User
        fields = ["username", "password"]

famous_quotes/app_auth/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from .forms import RegistrationForm
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import PasswordResetView

# Create your views here.


class RegisterView(View):
    template_name = "app_auth/registration.html"
    form_class = RegistrationForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes:home")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(
                request, f"Hello {username}. Your account successfully created."
            )
            return redirect(to="app_auth:signin")
        return render(request, self.template_name, {"form": form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = "app_auth/password_reset.html"
    email_template_name = "app_auth/password_reset_email.html"
    html_email_template_name = "app_auth/password_reset_email.html"
    success_url = reverse_lazy("app_auth:password_reset_done")
    success_message = (
        "An email with instructions to reset your password has been sent to %(email)s."
    )
    subject_template_name = "app_auth/password_reset_subject.txt"

famous_quotes/app_auth/templates/app_auth/login.html
{% extends 'quotes/base.html' %}

{% block content %}

{% if messages %}

        {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}> {{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class='alert alert-danger' role='alert'>
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <h2>Login</h2>

    <form method="post" accept-charset="utf-8">
        {% csrf_token %}
            <div class="row">
                <div class="form-group col-xs-3">
                    <label>Username</label>
                    {{ form.username }}
                </div>
                <span>{{form.errors.username}}</span>
            </div>
            <div class="row">
                <div class="form-group col-xs-3">
                    <label>Password</label>
                    {{ form.password }}
                </div>
                <span>{{form.errors.password}}</span>
            </div>
            <div class="d-flex align-items-center flex-nowrap">
                <a href="{% url 'app_auth:password_reset' %}" class="me-2">Reset password</a>
            </div>
            <br>
            <input type="submit" value="Login" class="btn btn-primary">

    </form>

{% endblock %}

famous_quotes/app_auth/templates/app_auth/password_reset.html
{% extends 'quotes/base.html' %}

{% block content %}

    {% if form.errors and form.non_field_errors %}
    <div class='alert alert-danger' role='alert'>
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <h2>Password reset</h2>

    <form method="post" accept-charset="utf-8">
        {% csrf_token %}
            <div class="row">
                <div class="form-group col-xs-3">
                    <label>Email</label>
                    {{ form.email }}
                </div>
                <span>{{form.errors.email}}</span>
            </div>
            <input type="submit" value="Request password reset" class="btn btn-primary">

    </form>

{% endblock %}

famous_quotes/app_auth/templates/app_auth/password_reset_complete.html
{% extends 'quotes/base.html' %}

{% block content %}

        <h2>Your password successfully reset</h2>

        <a href="{% url 'quotes:home' %}" class="btn btn-primary">Go back to Main</a>
{% endblock %}

famous_quotes/app_auth/templates/app_auth/password_reset_confirm.html
{% extends 'quotes/base.html' %}

{% block content %}

    {% if form.errors and form.non_field_errors %}
    <div class='alert alert-danger' role='alert'>
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <h2>Enter new password</h2>

    <form method="post" accept-charset="utf-8">
        {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Save new password" class="btn btn-primary">

    </form>

{% endblock %}

famous_quotes/app_auth/templates/app_auth/password_reset_done.html
{% extends 'quotes/base.html' %}

{% block content %}

        <h2>Password reset request sent</h2>

        <p>We've sent you email with instructions how to reset your password.</p>

        <a href="{% url 'quotes:home' %}" class="btn btn-primary">Go back to Main</a>

{% endblock %}

famous_quotes/app_auth/templates/app_auth/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'app_auth:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'app_auth:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>Our Team</p>
{% endautoescape %}

famous_quotes/app_auth/templates/app_auth/registration.html
{% extends 'quotes/base.html' %}

{% block content %}

    <h2>Registration</h2>
    {% if form.errors and form.non_field_errors %}
    <div class='alert alert-danger' role='alert'>
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post" accept-charset="utf-8">
        {% csrf_token %}
            <div class="row">
                <div class="form-group col-xs-3">
                    <label>Username</label>
                    {{ form.username }}
                </div>
                <span>{{form.errors.username}}</span>
            </div>
            <div class="row">
                <div class="form-group col-xs-3">
                    <label>Email</label>
                    {{ form.email }}
                </div>
                <span>{{form.errors.email}}</span>
            </div>
            <div class="row">
                <div class="form-group col-xs-3">
                    <label>Password</label>
                    {{ form.password1 }}
                </div>
                <span>{{form.errors.password1}}</span>
            </div>
            <div class="row">
                <div class="form-group col-xs-3">
                    <label>Confirm password</label>
                    {{ form.password2 }}
                </div>
                <span>{{form.errors.password2}}</span>
            </div>
            <input type="submit" value="SignUp" class="btn btn-primary">

    </form>

{% endblock %}