famous_quotes/app_auth/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)
from . import views
from .forms import LoginForm

app_name = "app_auth"

urlpatterns = [
    path("signup/", views.RegisterView.as_view(), name="signup"),
    path(
        "signin/",
        LoginView.as_view(
            template_name="app_auth/login.html",
            form_class=LoginForm,
            redirect_authenticated_user=True,
        ),
        name="signin",
    ),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password_reset/", views.ResetPasswordView.as_view(), name="password_reset"),
    path(
        "password_reset/done/",
        PasswordResetDoneView.as_view(
            template_name="app_auth/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password_reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="app_auth/password_reset_confirm.html",
            success_url="/auth/password_reset/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password_reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="app_auth/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

famous_quotes/famous_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

"""
URL configuration for famous_quotes project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("quotes.urls")),
    path("auth/", include("app_auth.urls")),
]

famous_quotes/quotes/urls.py
from django.urls import path

from .views import QuotesListView, AuthorDetailView, AuthorCreateView, QuoteCreateView

app_name = "quotes"

urlpatterns = [
    path("", QuotesListView.as_view(), name="home"),  # quotes:home
    path(
        "author/<slug:slug>/", AuthorDetailView.as_view(), name="author"
    ),  # quotes:author
    path(
        "add-author", AuthorCreateView.as_view(), name="add_author"
    ),  # quotes:add_author
    path("add-quote", QuoteCreateView.as_view(), name="add_quote"),  # quotes:add_quote
]

famous_quotes/quotes/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.


class Author(models.Model):
    fullname = models.CharField(max_length=120, unique=True)
    born_date = models.DateField()
    born_location = models.CharField(max_length=150)
    description = models.TextField(blank=True)
    slug = models.SlugField(null=True, unique=True)

    def __str__(self):
        return self.fullname

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.fullname)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        # formatted_name = self.fullname.replace(" ", "-")
        return reverse("quotes:author", kwargs={"slug": self.slug})


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    tags = models.ManyToManyField(Tag, related_name="quotes")

    def __str__(self):
        return self.tags

famous_quotes/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, DateField, DateInput, Textarea
from datetime import date

from .models import Author, Quote


class AddAuthorForm(ModelForm):
    fullname = CharField(
        max_length=120, required=True, widget=TextInput(attrs={"class": "form-control"})
    )
    born_date = DateField(
        widget=DateInput(attrs={"class": "form-control", "placeholder": "yyyy-mm-dd"})
    )
    born_location = CharField(
        max_length=150, widget=TextInput(attrs={"class": "form-control"})
    )
    description = CharField(widget=Textarea(attrs={"class": "form-control"}))

    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]


class AddQuoteForm(ModelForm):
    # quote = CharField(required=True, widget=TextInput(attrs={"class": "form-control"}))
    # author = DateField(widget=DateInput(attrs={"class": "form-control"}))
    # tags = CharField(widget=TextInput(attrs={"class": "form-control"}))
    class Meta:
        model = Quote
        fields = ["quote", "author", "tags"]

famous_quotes/quotes/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator

from .models import Quote, Author
from .forms import AddAuthorForm, AddQuoteForm


def author(request):
    return render(request, template_name="quotes/author.html", context={})


class QuotesListView(ListView):
    model = Quote
    template_name = "quotes/index.html"
    context_object_name = "quotes"
    paginate_by = 10
    queryset = Quote.objects.all()

    def get_queryset(self):
        return Quote.objects.select_related("author").all()


class AuthorDetailView(DetailView):
    model = Author
    template_name = "quotes/author.html"
    context_object_name = "author"


class AuthorCreateView(LoginRequiredMixin, CreateView):
    model = Author
    template_name = "quotes/add_author.html"
    form_class = AddAuthorForm
    success_url = reverse_lazy("quotes:home")


class QuoteCreateView(LoginRequiredMixin, CreateView):
    model = Quote
    template_name = "quotes/add_quote.html"
    form_class = AddQuoteForm
    success_url = reverse_lazy("quotes:home")

famous_quotes/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}

    <h2>Add new author</h2>

    <form action="{% url 'quotes:add_author' %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="mb-3">
             <label class="form-label">Fullname</label>
            {{ form.fullname }}
        </div>
        <span>{{form.errors.fullname}}</span>
        <div class="mb-3">
             <label class="form-label">Born date</label>
            {{ form.born_date }}
        </div>
        <span>{{form.errors.born_date}}</span>
        <div class="mb-3">
             <label class="form-label">Born location</label>
            {{ form.born_location }}
        </div>
        <span>{{form.errors.born_location}}</span>
        <div class="mb-3">
          <label class="form-label">Description</label>
            {{ form.description }}
        </div>
        <span>{{form.errors.description}}</span>
            <input type="submit" value="Add" class="btn btn-primary">

    </form>

{% endblock %}

famous_quotes/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block content %}

    <h2>Add new quote</h2>

    <form action="{% url 'quotes:add_quote' %}" method="post" accept-charset="utf-8">
        {% csrf_token %}
        <div class="mb-3">
             <label class="form-label">Quote</label>
            {{ form.quote }}
        </div>
        <span>{{form.errors.quote}}</span>
        <div class="mb-3">
             <label class="form-label">Author</label>
            {{ form.author }}
        </div>
        <span>{{form.errors.author}}</span>
        <div class="mb-3">
             <label class="form-label">Tags</label>
            {{ form.tags }}
        </div>
        <span>{{form.errors.tags}}</span>
            <input type="submit" value="Add" class="btn btn-primary">

    </form>

{% endblock %}

famous_quotes/quotes/templates/quotes/author.html
{% extends 'quotes/base.html' %}

{% block content %}
    <div class="author-details">

        <h3 class="author-title">{{ author.fullname }}</h3>
        <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span>
            <span class="author-born-location">{{ author.born_location }}</span></p>
        <p><strong>Description:</strong></p>
        <div class="author-description">{{ author.description }}
        </div>

    </div>
{% endblock %}

famous_quotes/quotes/templates/quotes/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/main.css' %}">
</head>
<body>
    <div class="container">
       <div class="row header-box">
           <div class="col-md-8">
                 <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape {{msg}}</a>
                </h1>
           </div>
           <div class="col-md-4">
            <div class="d-flex align-items-center flex-nowrap">
                {% if user.is_authenticated %}
                    <a href="{% url 'quotes:add_author' %}" class="me-2">Add author</a>
                    <a href="{% url 'quotes:add_quote' %}" class="me-2">Add quote</a>
                    <form action="{% url 'app_auth:logout' %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link ms-2">Log Out</button>
                    </form>
                {% else %}
                    <a href="{% url 'app_auth:signup' %}" class="me-2">SignUp</a>
                    <a href="{% url 'app_auth:signin' %}" class="ms-2">Login</a>
                {% endif %}
            </div>
</div>

       </div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

famous_quotes/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}

    <div class="row">
        <div class="col-md-8">

            {% for quote in quotes %}
            <div class="quote" itemscope="" >
                <span class="text" itemprop="text">{{ quote.quote }}</span>
                <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
                    <a href="{{ quote.author.get_absolute_url }}">(about) </a>
                </span>
                <div class="tags">
                    Tags:
                    {% for tag in quote.tags.all %}
                    <a class="tag" href=#>{{ tag.name }}</a>
                    {% endfor %}

                </div>
            </div>
            {% endfor %}

            {% if is_paginated %}
            <nav>
                <ul class="pager">
                    {% if page_obj.has_previous %}

                    <li class="previous">
                        <a href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">←</span> Previous</a>
                    </li>
                    {% endif %}
                    {% if page_obj.has_next %}

                        <li class="next">
                            <a href="?page={{ page_obj.next_page_number }}">Next <span aria-hidden="true">→</span></a>
                        </li>
                    {% endif %}

                </ul>
            </nav>
            {% endif %}

        </div>

    </div>

{% endblock %}